### ISSUE TITLE
Question !! Which tensorflow does it work with.

### ISSUE THREAD

**Issue by nikhilchh** [taki0112/UNIT-Tensorflow#1]
I tried with latest and got this issue:

ValueError: Variable share_encoder/resblock_0/res1/conv2d/kernel already exists, disallowed. Did you mean to set reuse=True or reuse=tf.AUTO_REUSE in VarScope? Originally defined at:

UNIT-Tensorflow-master/UNIT.py", line 155, in generate_a2b
    shared = self.share_encoder(out, self.is_training, reuse=True)

**Comment by taki0112** [comment]
fixed it
