### ISSUE TITLE
GPU supprot

### ISSUE THREAD

**Issue by reborm** [taki0112/UNIT-Tensorflow#2]
Hi, thank you for your share. When I run this code, I find that this code can not make use of gpu, even if i run the 'main_multi_gpu.py'

**Comment by taki0112** [comment]
Do you mean not to use gpu?

Have you checked "watch -n 0.1 nvidia-smi"?

**Comment by reborm** [comment]
Hi, I have a computer with cuda8.0 installed, but I only find this code running in cpu version. Could please tell me how to solve it ?  Thank you very much.

**Comment by taki0112** [comment]
Check this

1. pip install `tensorflow-gpu`  (do not install `tensorflow`)

2. set gpu_num
ex) export CUDA_VISIBLE_DEVICES=0,1,2,3

3. Try it
python main_multi_gpu.py --gpu_num 4 --batch_size 1

**Comment by reborm** [comment]
Sorry, it doesn't work

**Comment by taki0112** [comment]
Well, I'm running well ...
What is the GPU version?

**Comment by reborm** [comment]
My GPU is Nvidia Geforce 1070, Cuda version is 8.0, cudnn version is 5.1.

**Comment by reborm** [comment]
Hi, I suddenly found that I run this code in python2.7, which makes me feel very embarrassed. When I switch to python3, my gpu is now working. Additionly, the tensorflow I used in python3 is 1.2, but this version doesn't hava leaky_relu and instance_norm, one needs to add these two functions.

**Comment by littlealili** [comment]
Could you please send me a training set? I try to run the code by https://github.com/mingyuliutw/UNIT/tree/master/datasets/gta2city
but it has some problems. My email is 2986709061@qq.com,thank you very much!
